---
abstract: '(DEPRECATED) Validate nested data structures with nested structure'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
generated_by: 'Dist::Zilla version 1.093000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Schema
requires:
  Data::Dumper: 0
  Data::ModeMerge: 0
  Digest::MD5: 0
  File::Slurp: 0
  FindBin: 0
  List::MoreUtils: 0
  Moose: 0
  Scalar::Util: 0
  Storable: 0
  Test::Exception: 0
  Test::More: 0
  YAML::Syck: 0
  multidimensional: 0
  bareword::filehandles: 0
version: 0.135
